# Generated by Django 4.2.10 on 2024-03-08 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='Default_pfp.jpg', null=True, upload_to='')),
                ('employee_id', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('name_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=20, null=True)),
                ('height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True)),
                ('gsis_no', models.CharField(blank=True, max_length=20, null=True)),
                ('pagibig_no', models.CharField(blank=True, max_length=20, null=True)),
                ('philhealth_no', models.CharField(blank=True, max_length=20, null=True)),
                ('sss_no', models.CharField(blank=True, max_length=20, null=True)),
                ('tin_no', models.CharField(blank=True, max_length=20, null=True)),
                ('agency_em', models.CharField(blank=True, max_length=100, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=50, null=True)),
                ('residential_house_no', models.CharField(blank=True, max_length=10, null=True)),
                ('residential_street', models.CharField(blank=True, max_length=100, null=True)),
                ('residential_subd', models.CharField(blank=True, max_length=100, null=True)),
                ('residential_brgy', models.CharField(blank=True, max_length=100, null=True)),
                ('residential_city', models.CharField(blank=True, max_length=100, null=True)),
                ('residential_province', models.CharField(blank=True, max_length=100, null=True)),
                ('residential_zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('permanent_house_no', models.CharField(blank=True, max_length=10, null=True)),
                ('permanent_street', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_subd', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_brgy', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_city', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_province', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('spouse_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_name_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('spouse_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_employer', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_business_address', models.CharField(blank=True, max_length=200, null=True)),
                ('spouse_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('elementary_education', models.CharField(blank=True, max_length=200, null=True)),
                ('secondary_education', models.CharField(blank=True, max_length=200, null=True)),
                ('father_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('father_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('mother_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
