# Generated by Django 4.2.10 on 2024-03-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
