# Generated by Django 4.2.10 on 2024-03-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0003_alter_attendancerecord_break_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='break_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='break_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='surplusHour_time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='surplusHour_time_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
