# Generated by Django 4.2.10 on 2024-03-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0003_alter_employee_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('day', models.CharField(max_length=10)),
                ('office_time_start', models.DateTimeField(blank=True, null=True)),
                ('office_time_end', models.DateTimeField(blank=True, null=True)),
                ('honorarium_time_start', models.DateTimeField(blank=True, null=True)),
                ('honorarium_time_end', models.DateTimeField(blank=True, null=True)),
                ('servicecredit_time_start', models.DateTimeField(blank=True, null=True)),
                ('servicecredit_time_end', models.DateTimeField(blank=True, null=True)),
                ('overtime_time_start', models.DateTimeField(blank=True, null=True)),
                ('overtime_time_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=20),
        ),
    ]
