# Generated by Django 4.2.10 on 2024-03-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0004_officialtime_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialtime',
            name='semester_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='officialtime',
            name='honorarium_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officialtime',
            name='honorarium_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officialtime',
            name='office_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officialtime',
            name='office_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officialtime',
            name='overtime_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officialtime',
            name='overtime_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officialtime',
            name='servicecredit_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officialtime',
            name='servicecredit_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
