# Generated by Django 4.2.10 on 2024-03-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0004_alter_attendancerecord_break_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
