# Generated by Django 4.2.11 on 2024-03-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0006_alter_employee_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time_in', models.DateTimeField(blank=True, null=True)),
                ('break_in', models.DateTimeField(blank=True, null=True)),
                ('break_out', models.DateTimeField(blank=True, null=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('surplusHour_time_in', models.DateTimeField(blank=True, null=True)),
                ('surplusHour_time_out', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='officialtime',
            old_name='honorarium_time_end',
            new_name='official_honorarium_time_in',
        ),
        migrations.RenameField(
            model_name='officialtime',
            old_name='honorarium_time_start',
            new_name='official_honorarium_time_out',
        ),
        migrations.RenameField(
            model_name='officialtime',
            old_name='office_time_end',
            new_name='official_office_in',
        ),
        migrations.RenameField(
            model_name='officialtime',
            old_name='office_time_start',
            new_name='official_office_out',
        ),
        migrations.RenameField(
            model_name='officialtime',
            old_name='overtime_time_end',
            new_name='official_overtime_time_in',
        ),
        migrations.RenameField(
            model_name='officialtime',
            old_name='overtime_time_start',
            new_name='official_overtime_time_out',
        ),
        migrations.RenameField(
            model_name='officialtime',
            old_name='servicecredit_time_end',
            new_name='official_servicecredit_time_in',
        ),
        migrations.RenameField(
            model_name='officialtime',
            old_name='servicecredit_time_start',
            new_name='official_servicecredit_time_out',
        ),
    ]
