# Generated by Django 4.2.11 on 2024-03-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0006_alter_attendancerecord_break_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
