# Generated by Django 4.2.11 on 2024-03-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0007_alter_employee_employment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialtime',
            name='official_honorarium_time_in',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='officialtime',
            name='official_honorarium_time_out',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='officialtime',
            name='official_office_in',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='officialtime',
            name='official_office_out',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='officialtime',
            name='official_overtime_time_in',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='officialtime',
            name='official_overtime_time_out',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='officialtime',
            name='official_servicecredit_time_in',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='officialtime',
            name='official_servicecredit_time_out',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
    ]
