# Generated by Django 4.2.11 on 2024-04-23 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hris', '0008_alter_officialtime_official_honorarium_time_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_data', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hris.attendancerecord')),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
